Page({
    data:{
        legends:[
            {
                name:'阿卡丽',
                title:'刺客'
            },
            {
                name:'盖伦',
                title:'战士'
            },
            {
                name:'亚索',
                title:'快乐风男'
            },
            {
                name:'火男',
                title:'烧烤'
            }
        ]
    }
})